### ISSUE TITLE
Wiki linking

### ISSUE THREAD

**Issue by viaahmed** [Kholid060/notething#3]
**Is your feature request related to a problem? Please describe.**
I have used Roam Research, Obsidian, Logseq.

They use [[link text here]] for linking notes. Is is possible in Notething?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I also want to know have experienced any of those note making apps?

**Comment by Kholid060** [comment]
You can linking notes by using `@@`

**Comment by viaahmed** [comment]
The problem is, whether is it possible to link 'uncreated' notes
